Feature/forum
Waldo33/middle.game.praktikum.yandex pull request #10
Opened 2024-10-22 17:38 UTC by spiritius

### Какую задачу решаем

**Вёрстка страницы форума**

1. Сделать роут для страницы форума
2. Сверстать экраны форума:
- экран создания топика,
- экран со всем топиками,
- экран одного топика с комментами,
- функциональность добавления комментария к топику.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-10-23 06:44 UTC, galnikolai requested changes

2024-10-23 06:44 UTC, galnikolai commented on packages/client/src/pages/ForumPage/ui/ForumTable.tsx
> +            <TableRow key={item.id}>
Можно вынести в отдельный компонент

2024-10-23 06:44 UTC, galnikolai commented on packages/client/src/pages/ForumPage/ui/ForumTable.tsx
> +    <>
Fragment здесь лишний

2024-10-23 06:44 UTC, galnikolai commented on packages/client/src/pages/ForumTopicPage/types.tsx
Не уверен, что лучше выносить типы в отдельный файл, кажется, что часто они используются единожды, а появляются дополнительный импорты

2024-10-23 06:44 UTC, galnikolai commented on packages/client/src/pages/ForumPage/ui/ForumPagination.tsx
> +    <>
Тут тоже лишний fragment

2024-10-23 06:44 UTC, galnikolai commented on packages/client/src/pages/ForumPage/ui/ForumPage.tsx
> +            <Link to="/forum/add">создать тему →</Link>
Есть файл с роутам - стоит использовать константы

2024-10-23 06:44 UTC, galnikolai commented on packages/client/src/pages/ForumTopicPage/ui/CommentForm.tsx
> +const formSchema = z.object({
Есть файл validationRules, стоит вынести валидацию туда

2024-10-23 06:44 UTC, galnikolai commented on packages/client/src/pages/ForumTopicPage/ui/Comments.tsx
> +    <>
фрагментик)

2024-10-23 14:59 UTC, galnikolai requested changes

2024-10-23 14:59 UTC, galnikolai commented on packages/client/src/shared/config/routes.ts
> +  FORUM_ADD: '/forum/add',
Последняя небольшая правка я бы все таки вынес без слеша`FORUM_ADD: 'add',` так как реакт роутер абсолютные пути для детей не поддерживает, и использовал в линках ``${ROUTES.FORUM}/${ROUTES.FORUM_ADD}`` и соответственно добавил бы в роутер `path: ROUTES.FORUM_ADD,`

2024-10-23 15:22 UTC, galnikolai requested changes

2024-10-23 15:22 UTC, galnikolai commented on packages/client/src/pages/ForumTopicPage/ui/CommentForm.tsx
> +    const file = (document.getElementById('file') as HTMLInputElement)
В реакте есть хук useRef (https://ru.legacy.reactjs.org/docs/hooks-reference.html#useref)

Можно вместо прямых манипуляций с дом использовать хук примерно так:

`  
const fileInputRef = useRef<HTMLInputElement | null>(null)

  function onSubmit(values: z.infer<typeof formSchema>) {
    const file = fileInputRef.current?.files?.[0] 
    console.log({ ...values, file }) 
  }
  
  <Input ref={fileInputRef} id="file" type="file" />

`

2024-10-23 17:26 UTC, galnikolai approved these changes

2024-10-24 07:09 UTC, kyzinatra commented on packages/client/src/pages/ForumAddTopic/ui/ForumForm.tsx
> +    resolver: zodResolver(formSchema),
Отлично! Круто, что вы испольузете `useForm` и `zdo`

2024-10-24 07:10 UTC, kyzinatra commented on packages/client/src/pages/ForumAddTopic/ui/ForumForm.tsx
> +    console.log({ ...values, file })
Логи стоит убрать из прод версии

2024-10-24 07:12 UTC, kyzinatra approved these changes
Отлично! Хорошая верстка front части форума. Понравилась реализация форм. Ваша работа приянта! Желаю успехов в дальнейшем обучении

2024-10-24 08:54 UTC, spiritius commented
> Отлично! Хорошая верстка front части форума. Понравилась реализация форм. Ваша работа приянта! Желаю успехов в дальнейшем обучении

Спасибо! Стараемся (крутимся как лягушки в кузинатре)

2024-10-24 08:54 UTC, merged