13 Сверстать страницу пользователя
Waldo33/middle.game.praktikum.yandex pull request #11
Opened 2024-10-23 02:24 UTC by marie-uglova

### Какую задачу решаем
13 Сверстать страницу пользователя, вывод данных о пользователе, возможность поменять аватар и сменить пароль

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-10-23 15:05 UTC, Waldo33 requested changes
Ты молодец, видно что проделана большая работа:)
Осталось разобраться с некоторыми моментами

2024-10-23 15:05 UTC, Waldo33 commented on packages/client/src/pages/ProfilePage/ui/ProfileAvatar.tsx
> +    avatarUrl = 'https://ya-praktikum.tech/api/v2/resources' + avatar
Если не ошибаюсь, то Николай ранее уже выносил ссылку на api в энвы, можно отдельно вынести ссылку на ресурсы

Так же предлагаю все это вынести в отдельный компонент Avatar, куда можно будет прокинуть url и name, в теории это может потом переиспользоваться на Форуме и в Лидерборде

```
<Avatar className="profile__avatar">
    <AvatarImage src={avatarUrl} />
    <AvatarFallback className="profile__fallback">
      {login?.charAt(0)}
    </AvatarFallback>
</Avatar>
```

По идее бы такое лежало где нибудь в entities или features, но в нашем придется ложить в widgets
Логику по получению полной ссылки на аватар можно вынести в хелпер

```
const getFullAvatarUrl = (url) => `${RESOURSES_ENV}${url}`
```

2024-10-23 15:05 UTC, Waldo33 commented on packages/client/src/pages/ProfilePage/ui/ProfileAvatar.tsx
> +import './ProfilePage.scss'
Советую все же переделать под `ProfilePage.module.scss` и использовать так
```
import s from './ProfilePage.scss'
...
<div className={s.file} />
```

Это поможет изолировать все классы данного модуля внутри и избежать коллизии имен в будущем, все же как по мне это проще поддерживать чем БЭМ

2024-10-23 15:05 UTC, Waldo33 commented on packages/client/src/processes/profile/api/profileApi.ts
> +export const changeAvatar = async (credentials: FormData) => {
Смена аватара не относится к авторизации, по хорошему всю эту логику связанную с аватаром вынести в widgets/Avatar
Так же здесь ты передаешь в аргументах не credentials, а data - предлагаю переименовать

2024-10-23 15:05 UTC, Waldo33 commented on packages/client/src/pages/ProfilePage/ui/ProfileAvatar.tsx
> +  const onChange = async (evt: React.SyntheticEvent) => {
В React мы можем работать с DOM через useRef

```
const formRef = useRef<HTMLFormElement | null>(null)
const inputFileRef = useRef<HTMLInputElement | null>(null)

const handleFileChange = async () => {
    const inputFile = inputFileRef.current
    const form = formRef.current

    if (!inputFile?.files?.length || !form) return

    const formData = new FormData(form)
    formData.append('avatar', inputFile.files[0])

    try {
        const resultAction = await changeAvatar(formData)
        if (resultAction) {
          toast({ description: 'Аватар успешно изменён' })
        }
      } catch (error) {
        toast({ description: 'Произошла ошибка при смене аватара', variant: 'destructive' })
      }
    }
```

Далее я вижу следующие шаги к улучшению - вынесение всей логики смены аватара в хук + оборачивание запроса в try/catch чтоб перехватывать ошибку которую ты возвращаешь
```
export const useAvatarUpload = () => {
  const formRef = useRef<HTMLFormElement | null>(null);
  const inputFileRef = useRef<HTMLInputElement | null>(null);
  const toast = useToast();

  const handleAvatarChange = async () => {
    const inputFile = inputFileRef.current;
    const form = formRef.current;

    if (!inputFile?.files?.length || !form) return;

    const formData = new FormData(form);
    formData.append('avatar', inputFile.files[0]);

    try {
       const result = await changeAvatar(formData)
       if(result) {
          toast({
            description: 'Аватар успешно изменён',
          });
       }
    } catch (e) {
       toast({
        description: 'Произошла ошибка при смене аватара',
        variant: 'destructive',
       });
    }
  };

  return { formRef, inputFileRef, handleAvatarChange };
};
```

Эти изменения позволят сократить количество кода в компоненте и сделают его чище

2024-10-23 15:05 UTC, Waldo33 commented on packages/client/src/pages/ProfilePage/ui/ProfilePassword.tsx
> +            <Button className="w-full" type="submit">
Shadcn предлагают вот так оформить состояние [загрузки](https://ui.shadcn.com/docs/components/button#loading)

2024-10-23 15:05 UTC, Waldo33 commented on packages/client/src/pages/ProfilePage/ui/ProfileData.tsx
> +  const user = useSelector(selectUser),
Если после получения юзера проверить, что он действительно есть, то можно избежать ненужных optional chaining

```
const user = useSelector(selectUser)

if(!user) {
   return (
      // возвращаем состояние загрузки
   )
}

// далее здесь в коде мы уже гарантированно имеем объект user
```

2024-10-23 15:05 UTC, Waldo33 commented on packages/client/src/pages/ProfilePage/ui/ProfileData.tsx
> +            {login && (
Выглядит так, словно можно все эти поля мапить, но можно немного поразмышлять как:)

```
const userFormLabels: Record<keyof User, string> = {
   login: "Логин",
   secondName: "Фамилия",
   ...
}
const userFormFields = Object.entries(userFormLabels).map(([key, label]) => ({
   value: user[key],
   label,
})).filter(({value}) => value !== undefined)

// Далее мы имеем структуру данных которую можем превращать в TableRow
<div className="profile__container">
        <Table>
          <TableBody>
              {userFormFields.map(({ label, value }) => (
                 <TableRow>
                    <TableCell className="font-medium">{label}</TableCell>
                    <TableCell className="text-right">{value}</TableCell>
                  </TableRow>
              ))}
          </TableBody>
    </Table>
  </div>
```

А еще еще раз скажу вдовесок, что использование i18next значительно бы облегчило работу с лэнгами :)
p.s. но мы его пока не используем

```
const { t } = useTranslation("translation", { keyPrefix: "user" })
// явно задаем какие поля должны быть в форме
const userFormFields: Array<keyof User> = ['login', 'secondName', ...]

// Далее мы имеем структуру данных которую можем превращать в TableRow
<div className="profile__container">
        <Table>
          <TableBody>
              {userFormFields.map((value) => (
                 <TableRow>
                    <TableCell className="font-medium">{t(value)}</TableCell>
                    <TableCell className="text-right">{value}</TableCell>
                  </TableRow>
              ))}
          </TableBody>
    </Table>
  </div>
```
```

2024-10-23 15:05 UTC, Waldo33 commented on packages/client/src/pages/ProfilePage/ui/ProfileData.tsx
> +            {login && (
Опять же саму логику можно вынести в какой-нибудь красивый хук:)

2024-10-25 07:21 UTC, Waldo33 commented on packages/client/src/pages/ProfilePage/ui/ProfileData.tsx
> +  const userDataLabels = {
Можно типизировать вот этот объект, а следующий (userFormFields) не потребуется, так как тип вычислится сам примерно так 
```
type UserDataLabels = Record<keyof User, string>
const userDataLabels: UserDataLabels = { ... }
```

Возможно стоит подумать над тем чтобы переместить тип User к тебе на уровень pages или спустить таблицу с юзерами вместе с типом User в widgets

2024-10-25 07:21 UTC, Waldo33 commented on packages/client/src/pages/ProfilePage/ui/AvatarUpload.ts
> +export const useAvatarUpload = () => {
Так как хук это не ui, его можно вынести из сегмента ui в сегмент lib/hooks например

и назвать файл по названию хука - useAvatarUpload

2024-10-25 08:49 UTC, Waldo33 commented on packages/client/src/pages/ProfilePage/ui/ProfileData.tsx
> +  const userDataLabels = {
Покопался, предлагаю логику по соединению словаря и объекта с данными вынести в хелпер
Думаю может в будущем еще где-нибудь пригодиться:)
```
type Dictionary<T> = Partial<Record<keyof T, string>>;

type ResultItem<T> = {
  value: T[keyof T];
  label: string;
  key: keyof T;
}

function matchDictionaryAndData<T>(
  dictionary: Dictionary<T>,
  data: T
): ResultItem<T>[] {
  return (Object.keys(dictionary) as Array<keyof T>).map((key) => ({
    value: data[key],
    label: dictionary[key] as string,
    key,
  }));
}
```

2024-10-27 16:53 UTC, Waldo33 approved these changes

2024-10-28 17:21 UTC, Aliskhan7 commented on packages/client/src/widgets/avatar/avatarApi.ts
> +
нужно еще ловить ошибки, если запрос не пройдет

2024-10-28 17:23 UTC, Aliskhan7 commented on packages/client/src/processes/profile/api/profileApi.ts
> +}
можно еще попробовать использовать блок catch

2024-10-29 21:58 UTC, merged