Feature/hook auth
Waldo33/middle.game.praktikum.yandex pull request #14
Opened 2024-11-03 10:15 UTC by spiritius

### Какую задачу решаем

Авторизация должна проверяться через отдельно написанный Hook или HOC (на ваш выбор, можно использовать сразу оба)

2024-11-04 08:37 UTC, Waldo33 requested changes

2024-11-04 08:37 UTC, Waldo33 commented on packages/client/src/shared/hooks/useAuth.ts
> +import { selectIsAuthenticated } from '@processes/auth/model/selectors'
Нехорошо с верхнего уровня на нижний импортировать что-то

Предлагаю ProtectedRoute перенести в Processes, так как он используется только в роутере, который находится в processes - тогда этой порочной связи не будет

2024-11-04 08:40 UTC, Waldo33 requested changes

2024-11-04 08:40 UTC, Waldo33 commented on packages/client/src/widgets/intro/Intro.tsx
>          <div className={s['num']}>42</div>
Можно эти данные заодно доставать из localStorage

2024-11-04 08:40 UTC, Waldo33 commented on packages/client/src/widgets/menu/Menu.tsx
> +          <li key={index}>
Понимаю что этот список в процессе пока не изменяется, но предлагаю сразу учить себя не использовать index в качестве ключа. Давай лучше допустим что url у нас уникальное значение и будем использовать его в качестве ключа.

2024-11-06 15:34 UTC, spiritius commented on packages/client/src/widgets/intro/Intro.tsx
>          <div className={s['num']}>42</div>
Зачем? Имя из стора (нет лишних сетевых запросов), а без соединения с сетью должна работать только игра, разве нет? 
Плюс, после логина на mainPage не вижу в localStorage ничего 🤔

2024-11-06 19:38 UTC, galnikolai commented on packages/client/src/widgets/intro/Intro.tsx
>          <div className={s['num']}>42</div>
`<div className={s['num']}>42</div>`

я так понимаю, что Женя про лучший счет

2024-11-06 21:20 UTC, Waldo33 commented on packages/client/src/widgets/intro/Intro.tsx
>          <div className={s['num']}>42</div>
Да, именно так, я кладу после игры лучший счет в localStorage, его можно оттуда доставать как будто

2024-11-07 04:28 UTC, spiritius commented on packages/client/src/widgets/intro/Intro.tsx
>          <div className={s['num']}>42</div>
обновила (из "цитаты" не понятно о чем речь просто))

2024-11-07 06:51 UTC, galnikolai approved these changes

2024-11-08 06:35 UTC, Waldo33 approved these changes

2024-11-08 06:36 UTC, merged