Добавлен Service Worker
Waldo33/middle.game.praktikum.yandex pull request #15
Opened 2024-11-05 21:15 UTC by Waldo33

### Какую задачу решаем
Добавлен Service Worker для кэширования статики и запросов для работы в офлайн

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-11-09 15:26 UTC, galnikolai approved these changes

2024-11-09 15:49 UTC, galnikolai commented on packages/client/service-worker.js
Не кэшируется авторизация, а оффлайн режиме невозможно попасть на странички под авторизацией

2024-11-09 16:16 UTC, Waldo33 commented on packages/client/service-worker.js
Не получилось эту проблему решить на текущий момент, но хочется к дедлайну хотя бы в таком виде это сдать

2024-11-09 19:06 UTC, kyzinatra requested changes
Вы отлично поработали над воркерами, но сейчас есть несколько проблем которые нужно поправить прежде чем идти дальше

2024-11-09 19:06 UTC, kyzinatra commented on packages/client/service-worker.js
> +  '/leaderboard',
Надо исправить: так как у вас spa то ссылки на все страницы будут отдавать index.html. Так что тут кэшируется одно и то же
Также сервис воркер не умеет смотреть в папки. Так что последние 2 записи не валидны
Стоит правильно кэшировать все статику и HTML, CSS, is

2024-11-09 19:06 UTC, kyzinatra commented on packages/client/service-worker.js
> +
Можно лучше: не стоит кэшировать все запросы. Стоит делать это выборочно. Только те, которые правда того стоят и которые нужно

2024-11-10 12:22 UTC, Waldo33 commented on packages/client/service-worker.js
> +
Столкнулся с проблемой, что не удается закэшировать запросы от API Яндекса, так что текущий вариант с кэшированием всего не везде помогает
Может будут предложения как лучше организовать кэширование запросов?

2024-11-10 12:23 UTC, Waldo33 commented on packages/client/service-worker.js
> +  '/leaderboard',
Поправил, добавил для подстраховки, если вдруг браузер в оффлайне подсчитает что роут не закэширован

2024-11-10 12:26 UTC, Waldo33 commented on packages/client/service-worker.js
> +
Удивительно, решил проверить и авторизация в оффлайне зарабатала:)

2024-11-11 06:47 UTC, kyzinatra commented on packages/client/service-worker.js
> +
Кажется. что запросы на API Яндекса обычно и не нужно кэшировать. Но если это все же какая-то статическая информация, то нужно разбираться почему оно его не кэширует. 
Возможно запрос отправляет не ваш сайт, а к примеру вы открываете попап с дургой ссылкой. Тогда кэширование работать не будет.

Возможно вы поставили заголовок no-cache в зпросе.
Если все это не правда и вы просто делаете fecth а он его не кэширует, то попробуйте сделать прокси до этого запроса через свой сервера. Такой вариант точно сработает, но в таком случае не смогу вам сказать почему именно происходит такая проблема. Но если так и не удастся выяснить, то пропингуйте меня еще раз тут @kyzinatra  и покажите строку с запросом который не кэшируется. Попробуем вместе разобраться

2024-11-11 06:48 UTC, kyzinatra commented on packages/client/service-worker.js
>    '/favicon-light.svg',
Все еще не закэширована статика. Сайт не сможет нормально работать без js и css. Попробуйте сбилдить сайт. В папке билд вы увидите то, как будет выглядеть ваш сайт на проде. Все эти файлы нужно закэшировать для нормальной работы сайта

2024-11-11 12:14 UTC, Waldo33 commented on packages/client/service-worker.js
> +
@kyzinatra Сделал При офлайне падает запрос, который отвечает за установку значения isAuth, то есть при офлайне всегда показывается форма авторизации и не получается зайти в игру

Сделал прокси для vite и nginx, но это не решило проблему
Так же попытался переписать кэширование, чтобы кэш запросов брался если нет интернета, а в остальных случаях отправлялся к апишке

![image](https://github.com/user-attachments/assets/9f7d959d-7081-4c1d-bcc9-fd3637f998c8)

2024-11-11 12:37 UTC, Waldo33 commented on packages/client/service-worker.js
>    '/favicon-light.svg',
Оно кэшируется при 'fetch', и все корректно отрабатывает, стили отображаются при оффлайне и js отрабатывает 
А названия остальных ассетов динамически меняется каждый билд, по типу `index.[hash].css`, не представляю как это статичными ссылками закэшировать

2024-11-11 12:50 UTC, kyzinatra commented on packages/client/service-worker.js
> +
Сейчас гляну

2024-11-11 12:52 UTC, Waldo33 commented on packages/client/service-worker.js
> +
С проксированием запросов в целом могу сюда изменения закинуть

2024-11-11 12:55 UTC, kyzinatra commented on packages/client/service-worker.js
>    '/favicon-light.svg',
Да, это правда, но так лучше не делать. Лучше кэшировать такие файлы в инстале.. Чтобы обрабатывать кэш в названиях файлов можно использовать скрипт при Билле который положит названия этих файлов в константу или файл. Можно как самому написать этот скрипт так и использовать готовые инструменты вроде workbox. 
Но в целом я понимаю, что это не очень приятная история, так что готов принять работу и с кэшированием через fetch. Только разберемся с проблемой с авторизацией, пофиксим ее и думаю работу можно будет принять.
Хотя все же рекомендую почитать про готовые инструменты для сервис воркеров

2024-11-11 13:33 UTC, Waldo33 commented on packages/client/service-worker.js
>    '/favicon-light.svg',
Изначально спрашивал про то, можно ли использовать workbox, вроде как сказали что нужно самому написать service worker

2024-11-11 15:30 UTC, kyzinatra commented on packages/client/service-worker.js
>    '/favicon-light.svg',
Да, понимаю. Тогда оставляю этот вопрос вам на будущее

2024-11-11 15:53 UTC, kyzinatra commented on packages/client/service-worker.js
> +
По поводу ошибки в запросе. Я немного потестил ваш service worker и проанализировал код. Я обнаружил только, что вы кэшируете `basic` запросы. А для экширования кросс-доменных запросов необходимо учитывать ответы типа "opaque". 
Попробуйте повыводить логи и потестить. На каком этапе что-то идет не так.
К сожалению больше ничего сказать не могу. Возможно наставник, который больше погружен в ваш проект сможет что-то увидеть, чего я не вижу. У меня к сожалению мало возможностей быстро определить проблему в этом плане. Чтобы сказать больше нужно с вами сидеть и разбираться в проекте(

Вообще говоря я часто на проде видел решение, когда локально в localStorage или IndexDB сохраняется информация о пользователе и потом используется для того, чтобы понять авторизован ли пользователь в оффлайн режиме. Решение может выглядеть немного костыльным, но в целом более чем рабочее. Так как мы хотим просто дать возможность играть в оффлайн кажется вполне рабочим вариантом.

2024-11-11 16:13 UTC, Waldo33 commented on packages/client/service-worker.js
> +
Рассматривал кстати сохранение в localStorage, но мне оно показалось костыльным и довольно уязвимым - ведь мы можем подделать данные в localStorage

2024-11-11 17:17 UTC, Waldo33 commented on packages/client/service-worker.js
> +
@kyzinatra добавил сохранение данных пользователя и их проверку при оффлайне

2024-11-11 17:37 UTC, Waldo33 commented on packages/client/service-worker.js
> +
Странно, локально отрабатывало как и задумано - авторизация не отображалось... слил и на превью снова вылезает авторизация

2024-11-11 19:41 UTC, kyzinatra commented on packages/client/service-worker.js
> +
> Рассматривал кстати сохранение в localStorage, но мне оно показалось костыльным и довольно уязвимым - ведь мы можем подделать данные в localStorage

На самом деле нет. Это делается только для отображения UI. Пользователю все равно приходят все страницы. Так что при желании он сможет открыть игру и так. А запросы которые чуствительны к данным все равно проходят через сервер где проверяется токен. Так что его подменить не выйдет

2024-11-11 19:42 UTC, kyzinatra commented on packages/client/service-worker.js
> +
> @kyzinatra добавил сохранение данных пользователя и их проверку при оффлайне

К сожалению не смогу просмотреть превью, так как нет доступов к vercel

2024-11-11 19:42 UTC, kyzinatra commented on packages/client/service-worker.js
> +
> Странно, локально отрабатывало как и задумано - авторизация не отображалось... слил и на превью снова вылезает авторизация

К сожалению не смогу просмотреть превью, так как нет доступов к vercel

2024-11-11 21:08 UTC, Waldo33 commented on packages/client/service-worker.js
> +
@kyzinatra я смог, решил проблему, пытался брать данные в thunk-е, перенес получение данных из localStorage в компонент и все заработало

2024-11-12 07:45 UTC, Waldo33 commented on packages/client/service-worker.js
>    '/favicon-light.svg',
@kyzinatra я добавил динамическую генерацию путей к ресурсам в свой плагин

2024-11-12 08:31 UTC, kyzinatra commented on packages/client/service-worker.js
> +
Здорово! Было бы круто, если бы дали ссылку на видео, тогда бы сейчас смогу принять работу. Если не получится, то чуть позже посмотрю. Можете пока отправить работу на проверку в системе

2024-11-12 08:31 UTC, kyzinatra commented on packages/client/service-worker.js
>    '/favicon-light.svg',
Здорово! Отличная работа!

2024-11-12 08:32 UTC, kyzinatra commented on packages/client/serviceWorkerBuildPlugin.ts
> +      if (entry.isDirectory()) {
Да, примернро так это и должно выглядеть. Отличная работа!

2024-11-12 11:52 UTC, kyzinatra commented on packages/client/service-worker.js
> +
@Waldo33  Вроде бы все хорошо, вы отлчино поработали. Можете пожалуйста отправить работу в личном кабинете. Я еще раз посмотрю и приму)

2024-11-12 11:54 UTC, Waldo33 commented on packages/client/service-worker.js
> +
Хотел заснять видео, но окей, тогда отправляю

2024-11-12 11:59 UTC, kyzinatra commented on packages/client/service-worker.js
> +
Видео посмотрел, спасибо

2024-11-12 12:12 UTC, kyzinatra approved these changes

2024-11-12 12:13 UTC, merged