Добавлено одно из описанных в уроках Web API - Fullscreen
Waldo33/middle.game.praktikum.yandex pull request #16
Opened 2024-11-05 21:32 UTC by marie-uglova

### Какую задачу решаем
Добавлено одно из описанных в уроках Web API - Fullscreen
Игру можно открыть в полноэкранном режиме.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-11-07 09:43 UTC, galnikolai requested changes

2024-11-07 09:43 UTC, galnikolai commented on packages/client/src/shared/hooks/useFullScreen.ts
<img width="838" alt="Снимок экрана 2024-11-07 в 12 00 52" src="https://github.com/user-attachments/assets/557d061b-9af2-4ab3-8e69-5a900501e169">


Насколько мне известно requestFullscreen достаточно, его поддерживают все браузеры, и добавлять обработку с префиксами moz, ms, webkit не обязательно, то же самое  с exitFullscreen,

<img width="838" alt="Снимок экрана 2024-11-07 в 12 06 26" src="https://github.com/user-attachments/assets/1f16ed34-cf78-45e7-bdda-da5114bf85e8">


в сафари на мобилке только есть какие-то особенности, а мы пока и не поддерживаем мобилку, на декстопе работает, проверил

2024-11-07 09:43 UTC, galnikolai commented on packages/client/src/pages/GamePage/ui/GamePage.tsx
> +  const fullScreen = useFullScreen()
`  const { showFullScreen, canvasContainerRef } = useFullScreen()
`
тут можно сделать деструктуризацию, для чистоты, чтобы не ссылаться объект

2024-11-07 09:43 UTC, galnikolai commented on packages/client/src/shared/hooks/useFullScreen.ts
> +  requestFullscreen: () => void
У методов веб апи возрвращается промис `requestFullscreen: () => Promise<void>`

2024-11-07 09:43 UTC, galnikolai commented on packages/client/src/shared/hooks/useFullScreen.ts
- Проверки `container as unknown as Document` - не очень чисто и лучше без unknown, undefined да там типы как будто и не нужны
- С учетом того, что метод для с префиксами можно не использовать, можно сильно уменьшить функцию 
- Было бы здорово добавить async/await для обработки ошибок
- Мне кажется здорово было бы знать состояние isFullScreen для более очевидного управления чтобы показывать/скрывать что-то в компонентах, навешивать разные классы для разных режимов экрана и тд. (можно навесит слушателей для события)


Как то примерно вот так вижу этот хук:

```
import { useRef, useCallback, useEffect, useState } from 'react';

interface UseFullScreenResult {
  canvasContainerRef: React.RefObject<HTMLDivElement>;
  showFullScreen: () => Promise<void>;
  isFullScreen: boolean;
}

export const useFullScreen = (): UseFullScreenResult => {
  const canvasContainerRef = useRef<HTMLDivElement | null>(null);
  const [isFullScreen, setIsFullScreen] = useState<boolean>(false);

  const showFullScreen = useCallback(async (): Promise<void> => {
    const container = canvasContainerRef.current;
    if (container) {
      try {
        if (!document.fullscreenElement) {
          await container.requestFullscreen();
          setIsFullScreen(true);
        } else if (document.exitFullscreen) {
          await document.exitFullscreen();
          setIsFullScreen(false);
        }
      } catch (error) {
        console.error('Ошибка в работе полноэкранного режима:', error);
      }
    }
  }, []);

  useEffect(() => {
    const handleFullscreenChange = (): void => {
      setIsFullScreen(!!document.fullscreenElement);
    };

    document.addEventListener('fullscreenchange', handleFullscreenChange);
    return () => {
      document.removeEventListener('fullscreenchange', handleFullscreenChange);
    };
  }, []);

  return { canvasContainerRef, showFullScreen, isFullScreen };
};

```

2024-11-07 09:43 UTC, galnikolai commented on packages/client/src/pages/GamePage/ui/GamePage.tsx
В полноэкранном режиме исчезает счет

2024-11-07 09:43 UTC, galnikolai commented on packages/client/src/shared/hooks/useFullScreen.ts
Здорово, что вынесла в хук🙂

2024-11-07 16:04 UTC, galnikolai approved these changes

2024-11-08 06:20 UTC, kyzinatra approved these changes
Отличная работа с fullscreen api. Понравилось, что вы вынесли логику в отдельный хук. Вопросов к работе у меня нет, все сделано хорошо

2024-11-08 08:56 UTC, merged