Added index: landing page
Waldo33/middle.game.praktikum.yandex pull request #3
Opened 2024-10-18 18:24 UTC by spiritius

### Какую задачу решаем

**Сверстать  главную страницу игры: мини-лендинг с презентацией игры**
Сверстать страницу, на которую попадает пользователь после авторизации. На странице присутствует описание игры и возможность перейти к форуму, лидерборду, профилю и игре.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-10-19 08:52 UTC, Waldo33 requested changes
Работа визуально выглядит очень круто!

По коду есть моменты которые можно улучшить, сделав его более читаемым

2024-10-19 08:52 UTC, Waldo33 commented on packages/client/index.html
> +    <link
Можно улучшить подключение шрифтов, сделав его более удобным:)
Как вариант, можем выкачать шрифты и подключить их в vite.config.js через плагин [vite-plugin-fonts
](https://www.npmjs.com/package/vite-plugin-fonts) Вот так через него выглядит подключение шрифтов из гугла

```
VitePluginFonts({
      google: {
        families: ['Source Sans Pro'],
      },
    }),
```

А вот так я у себя в рабочем проекте подключаю локально скачанные шрифты

```
VitePluginFonts({
      custom: {
        families: [
          {
            name: "Inter",
            local: "Inter",
            src: "./assets/fonts/*.ttf",
          },
        ],
        display: "auto",
        preload: true,
        injectTo: "body",
      },
    }),
```

2024-10-19 08:52 UTC, Waldo33 commented on packages/client/src/pages/MainPage/ui/MainPage.scss
> +    &__title {
У библиотеки shadcn есть компонент [Typography](https://ui.shadcn.com/docs/components/typography)
Возможно лучшим решением будет все шрифты через него регулировать?

2024-10-19 08:52 UTC, Waldo33 commented on packages/client/src/pages/MainPage/ui/MainPage.tsx
> +            <Card className="team__item">
Здесь можно сократить код, если создать объект и мапить из него карточки

```
const teammates = [
   {
      name: "Аня" Хлыстова",
      about: "пишет код, изучает react",
      imageText: "[img]",
      imageSrc: ""
   }
]

...

<section id="team" className="section team">
          <h4 className="section__title">команда</h4>
          <div className="grid grid-cols-1 md:grid-cols-2 md:max-w-[600px] gap-4">
            {teammates.map({ name, about, image, imageSrc }) => (
                <Card className="team__item">
                   <CardHeader>
                      <div className="team__item_img">
                          {imageSrc && <img src={imageSrc} />}
                          {!imageSrc && imageText}
                      </div>
                   </CardHeader>
                   <CardContent>
                      <p className="team__item_title">{name}</p>
                      <p className="team__item_descr">{about}</p>
                   </CardContent>
               </Card>
           )}
          </div>
</section>
```

Выглядит словно карточку team__item можно в отдельный компонент вынести, можно пока рядом со страницей положить если будешь делать

2024-10-19 08:52 UTC, Waldo33 commented on packages/client/src/pages/MainPage/ui/MainPage.tsx
> +                  <a href="/profile">профиль →</a>
Навигация в React делается с помощью Link, а не тэга a, если сделать навигацию через a будут проблемы

2024-10-19 08:52 UTC, Waldo33 commented on packages/client/src/pages/MainPage/ui/MainPage.tsx
> +        <section id="rules" className="section rules">
Можно по желанию повыносить части страницы на компоненты, это бы значительно подсократило код самой страницы

2024-10-19 08:59 UTC, spiritius commented on packages/client/index.html
> +    <link
>vite-plugin-fonts
>This package has been deprecated
пупупу
воспользуюсь unplugin-fonts от того же автора

2024-10-19 09:37 UTC, spiritius commented on packages/client/src/pages/MainPage/ui/MainPage.scss
> +    &__title {
я так понимаю, под капотом компонента типографии используется тот же tailwind, так что не вижу смысла накидывать сверху что-то лишнее (а именно, компонент типографии shadcn). предлагаю задать для h1-h6 + p определенные стили в глобальном index.css и не мучиться

2024-10-19 10:03 UTC, spiritius commented on packages/client/src/pages/MainPage/ui/MainPage.tsx
> +        <section id="rules" className="section rules">
если эти компоненты используются только в одном месте, то не вижу смысла в усложнении структуры
страница не такая уж и большая)

2024-10-19 10:36 UTC, Waldo33 commented on packages/client/src/pages/MainPage/ui/MainPage.scss
> +    &__title {
Если есть компоненты готовые, почему бы их не использовать? 
Использование текстов будет легче, ведь не нужно будет для каждого текста стили задавать.

2024-10-19 10:37 UTC, spiritius commented on packages/client/src/pages/MainPage/ui/MainPage.scss
> +    &__title {
я к тому, что легче использовать простые теги <h1></h1>, чем компоненты вместо них

2024-10-19 10:40 UTC, Waldo33 commented on packages/client/src/pages/MainPage/ui/MainPage.tsx
> +        <section id="rules" className="section rules">
На текущий момент кажется что в одном месте. Но как минимум это сделает код страницы читаемее минимальными усилиями.

2024-10-19 10:41 UTC, spiritius commented on packages/client/src/pages/MainPage/ui/MainPage.scss
> +    &__title {
стили определим сами, исходя из дизайна данной страницы

2024-10-19 10:44 UTC, Waldo33 commented on packages/client/src/pages/MainPage/ui/MainPage.tsx
> +        <section id="rules" className="section rules">
Как минимум повторяющиеся куски можно вынести в компонент, в который можно будет прокинуть текст.
Например карточки со ссылками, с текстом и тд

2024-10-19 10:47 UTC, Waldo33 commented on packages/client/src/pages/MainPage/ui/MainPage.scss
> +    &__title {
Хорошо, замечание резолвлю, но предлагаю все же подумать над тем чтобы управлять шрифтами через Typography

2024-10-20 14:23 UTC, Waldo33 approved these changes

2024-10-20 16:36 UTC, merged