Добавлена OAuth авторизация через Яндекс
Waldo33/middle.game.praktikum.yandex pull request #30
Opened 2024-11-27 15:19 UTC by Waldo33

### Какую задачу решаем
Добавлена OAuth авторизация через Яндекс

### Скриншоты/видяшка (если есть)
![image](https://github.com/user-attachments/assets/e345fe82-374d-498d-80de-930f6490c5f7)

### TBD (если есть)
На Preview протестировать это не получится, так как в Callback URL добавлены только домен для прода и localhost. Есть возможность протестировать локально.

2024-11-28 17:16 UTC, galnikolai requested changes

2024-11-28 17:16 UTC, galnikolai commented on packages/client/src/processes/auth/hooks/useOAuthCodeHandle.ts
> +      signin(oAuthCode)
useEffect не поддерживает возвращение промиса, собственно, можно объявить асинхронную функцию внутри useEffect и уже ее вызывать

https://dev.to/sanjampreetsingh/why-async-callback-cannot-happen-in-react-useeffect-hook-ff

2024-11-28 18:33 UTC, Waldo33 commented on packages/client/src/processes/auth/hooks/useOAuthCodeHandle.ts
> +      signin(oAuthCode)
Но я же не передаю в useEffect асинхронную функцию, useEffect у меня принимает синхронную функцию, которая вызывает асинхронную

2024-11-28 18:35 UTC, Waldo33 commented on packages/client/src/processes/auth/hooks/useOAuthCodeHandle.ts
> +      signin(oAuthCode)
По крайней мере как я это вижу, в статье говорится про такой случай:

```jsx
useEffect(async () => {}, [])
```

Что конечно же является неприемлемым

2024-11-28 18:37 UTC, Waldo33 commented on packages/client/src/processes/auth/hooks/useOAuthCodeHandle.ts
> +      signin(oAuthCode)
Сам React аналогичный пример приводит если попробовать такую конструкцию сделать

<img width="761" alt="image" src="https://github.com/user-attachments/assets/0780985c-d7b5-4762-a90b-9103f9c1c32a">


> По крайней мере как я это вижу, в статье говорится про такой случай:
> 
> ```js
> useEffect(async () => {}, [])
> ```
> 
> Что конечно же является неприемлемым

2024-11-28 18:38 UTC, galnikolai requested changes

2024-11-28 18:38 UTC, galnikolai commented on packages/client/src/processes/auth/hooks/useOAuthCodeHandle.ts
> +      signin(oAuthCode)
```
const signin = async (code: string) => {
    await signinWithOauthToken(code, getCurrentHostWithPort())
    dispatch(userThunk())
    setParams('')
  }
```
вот эта функция асинхронная

2024-11-28 18:38 UTC, Waldo33 commented on packages/client/src/processes/auth/hooks/useOAuthCodeHandle.ts
> +      signin(oAuthCode)
С другой стороны, возможно имеет смысл либо переместить функцию внутрь useEffect, либо мемоизировать, наверное я выберу вариант перенести внутрь и поправить нейминг, сейчас запушу результат.

2024-11-28 18:46 UTC, galnikolai approved these changes

2024-11-29 08:11 UTC, kyzinatra approved these changes
Отличная работа над OAuth форматом входа. Вы отлично постарались. Есть пару комментариев, но они не критичные

2024-11-29 08:11 UTC, kyzinatra commented on packages/client/src/app/App.tsx
> +  useOAuthCodeHandle()
Понравилось, что вы вынесли логику в отдельный хук

2024-11-29 08:11 UTC, kyzinatra commented on packages/client/src/processes/auth/api/authApi.ts
> +    console.log(error)
Стоит убрать логи в консоль и выводить их пользователю

2024-11-29 19:04 UTC, Waldo33 commented on packages/client/src/processes/auth/api/authApi.ts
> +    console.log(error)
Убрать консоль лог, добавил состояние загрузки и вывод тоста на ошибку

2024-11-30 19:16 UTC, merged