Feature/leaderboard api
Waldo33/middle.game.praktikum.yandex pull request #32
Opened 2024-11-28 14:58 UTC by marie-uglova

### Какую задачу решаем
Добавить API для лидерборда, вывести список игроков

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-11-29 10:47 UTC, galnikolai requested changes

2024-11-29 10:47 UTC, galnikolai commented on packages/client/src/widgets/leaderboardtable/LeaderboardTable.tsx
> +            <TableRow key={index}>
Все таки лучшей практикой использовать для key не index, а, например login, в данном случае

https://ru.legacy.reactjs.org/docs/lists-and-keys.html

2024-11-29 10:47 UTC, galnikolai commented on packages/client/src/widgets/leaderboardtable/LeaderboardTable.tsx
А почему решила вынести leaderboardеtable в widgets, а не положить рядом LeaderboardPage?

2024-11-29 10:47 UTC, galnikolai commented on packages/client/src/pages/GamePage/ui/GamePage.tsx
>    const onEndGame = () => {
Функция onEndGame вызывается до onUpdateScore и после завершения игры отсылает не обновленный лучший результат, можно перенести, например в onUpdateScore в конец функции

2024-11-29 10:47 UTC, galnikolai commented on packages/client/src/pages/GamePage/ui/GamePage.tsx
> +    const valuesResultGame = {
Компонент будет чище если убрать композицию атрибутов в leaderboardApi, передавая нужные аргументы в addUserToLeaderboard

2024-11-29 10:47 UTC, galnikolai commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +  interface UserDataProps {
Лучше писать интерфейсы вне компоненты, да и в целом, если объект не зависит от пропсов, обычно стоит вынести из компонента

2024-11-29 10:47 UTC, galnikolai commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +  interface UserDataProps {
```
export interface UserLeaderboardProps {
  data: {
    bestScore: number
    login: string | undefined
    avatar: string | undefined
  }
  ratingFieldName: string
}
```


```
  interface UserDataProps {
    data: {
      bestScore: number
      login: string | undefined
      avatar?: string | undefined
    }
  }
```

дублируется типизация, можно например оставить UserDataProps и переиспользовать внутри UserLeaderboardProps

2024-11-29 10:47 UTC, galnikolai commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +      const usersResultValues = {
Это тоже стоит вынести в запрос

2024-11-29 10:47 UTC, galnikolai commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +  const users: any[] = Array.from(userList)
Для чего здесь нужен  Array.from, вроде getLeaderboard возвращает массив?

2024-11-29 10:47 UTC, galnikolai commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +      const leaderboardDataValue = leaderboardData.map(
Не имеет особого смысла пробегать по массиву, что уменьшить вложенность, вместо этого можно при маппинге таблицы, деструктуризировать объект

```
 {list.map(({ data }, index) => {
            const { login, avatar, bestScore } = data
```

2024-12-01 15:54 UTC, marie-uglova commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +  const users: any[] = Array.from(userList)
Нет, объект. Без Array.from выдает ошибку list.map is not a function.

2024-12-01 16:16 UTC, Waldo33 commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +  const users: any[] = Array.from(userList)
А в каком виде объект возвращается?

2024-12-01 16:22 UTC, galnikolai requested changes

2024-12-01 16:22 UTC, galnikolai commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +  const [userList, setUserList] = useState('')
Можно добавить для стейта тоже типы

2024-12-01 16:22 UTC, galnikolai commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +  const users: any[] = Array.from(userList)
<img width="532" alt="Снимок экрана 2024-12-01 в 19 19 14" src="https://github.com/user-attachments/assets/4bd33851-5fc7-46f6-b3c5-b2d6aea1288c">

2024-12-01 16:22 UTC, galnikolai commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +  const users: any[] = Array.from(userList)
Там возникает ошибка потому что когда еще нет ответа уже пытается мапится массив, нужно добавить проверку на наличие массива и только в случае если он есть рисовать таблицу

2024-12-01 18:20 UTC, marie-uglova commented on packages/client/src/widgets/leaderboardtable/LeaderboardTable.tsx
Женя говорил, что возможно где-то будем переиспользовать.

2024-12-01 18:24 UTC, Waldo33 commented on packages/client/src/widgets/leaderboardtable/LeaderboardTable.tsx
Возможно, это было на уровне предположения:)
С одной стороны размазывать логику по проекту когда это не надо - плохо
С другой стороны таблица лидеров выглядит как полноценный компонент, почему бы сразу на уровень виджетов не вынести

2024-12-01 18:26 UTC, Waldo33 commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +  const users: any[] = Array.from(userList)
Вот не поверишь, сам предполагал что какой нибудь undefined мапить пытаемся

2024-12-01 18:32 UTC, Waldo33 reviewed
Предлагаю обратить внимание на следующие моменты, если есть время поправить
Как по мне некоторые из них, по типу использования any странных шаблонных литералов в типах - довольно критичны

2024-12-01 18:32 UTC, Waldo33 commented on packages/client/src/pages/GamePage/lib/helpers/index.ts
> +  key: `score-undefined` | `score-${number}` | 'bot-mode-score',
А что здесь произошло?
Это же типы, разве законно тут такое писать?

2024-12-01 18:32 UTC, Waldo33 commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +  const [userList, setUserList]: any[] = useState('')
any это плохо, у нас есть тип User, нужно типизировать

2024-12-01 18:32 UTC, Waldo33 commented on packages/client/src/processes/leaderboard/api/leaderboardApi.ts
> +  avatar?: string | undefined
В таких случаях нет нужды дописывать "| undefined", это и так знаком вопроса обозначено

2024-12-01 18:48 UTC, galnikolai requested changes

2024-12-01 18:48 UTC, galnikolai commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +  const [userList, setUserList]: any[] = useState('')
` const [userList, setUserList]: any[] = useState('')` тут лучше дефолтное значение или null  или пусто массив, чтобы не мутировать тип данных из строки в объект и типы лучше не any все таки и записывать через дженерики `useState<GameModes | null>(null)`

2024-12-01 18:48 UTC, galnikolai commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +        {userList ? <LeaderboardTable list={userList} /> : ''}
Если дефолтное значение будет массивом, то такая проверка `userList ?`  вернет true и даже когда массив пустой будет пытаться нарисовать таблицу - можно например проверить длину массива и привести ее к boolean, тогда будет работать корректно` !!userList.length `

2024-12-01 18:48 UTC, galnikolai commented on packages/client/src/widgets/leaderboardtable/LeaderboardTable.tsx
Я бы перенес к LeaderboardPage, не вижу пока что сценариев переиспользования, и как будто пока не переиспользуешь компонент и не предполагаешь где это будешь делать и не имеет смысла в виджеты выносить

2024-12-01 19:27 UTC, marie-uglova commented on packages/client/src/pages/GamePage/lib/helpers/index.ts
> +  key: `score-undefined` | `score-${number}` | 'bot-mode-score',
![000](https://github.com/user-attachments/assets/3c562088-f63b-4c53-8f5a-1aaff06071fc)
Мы теперь записываем bestScore с привязкой к id юзера, чтобы не было путаницы при смене аккаунта.
Есть какой-то способ избежать изменения типизирования?

2024-12-01 20:05 UTC, galnikolai approved these changes

2024-12-02 06:17 UTC, Waldo33 commented on packages/client/src/pages/GamePage/lib/helpers/index.ts
> +  key: `score-undefined` | `score-${number}` | 'bot-mode-score',
Тогда это просто string по типам

2024-12-02 09:45 UTC, Waldo33 commented on packages/client/src/pages/GamePage/lib/helpers/index.ts
> +  key: `score-undefined` | `score-${number}` | 'bot-mode-score',
В compareScoreWithLocalStorage тип у key нужно поменять на string

2024-12-02 09:45 UTC, Waldo33 approved these changes

2024-12-02 15:51 UTC, merged