Authorization
Waldo33/middle.game.praktikum.yandex pull request #4
Opened 2024-10-18 18:54 UTC by galnikolai

### Какую задачу решаем

Вёрстка страницы логина 
Вёрстка страницы регистрации
Валидация на все формы
Логика авторизации

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-10-19 20:04 UTC, Waldo33 requested changes
Круто что добавил enum для роутов, я почему то в моменте передумал его добавлять из-за возможной вложенности роутов, но теперь понимаю что под вложенные роуты тоже можно будет сделать enum:)

2024-10-19 20:04 UTC, Waldo33 commented on packages/client/jest.config.js
> +    // '^@features/(.*)$': '<rootDir>/src/features/$1',
Подскажи, а для чего это комментировать?
Вроде алиасы не мешают, но если прям хочется явно их убрать - то надо удалить

2024-10-19 20:04 UTC, Waldo33 commented on packages/client/src/app/App.tsx
> +        <LoadingSpinner />
Можно не использовать тернарник, без него код выглядит немного более читаемым
Так же можно не сравнивать с undefined, ведь это falsy-значение
Так же можно сделать так чтобы селектор по умолчанию возвращал false
```
{!isAuthenticated && <LoadingSpinner />}
{isAuthenticated && <RouterProvider router={router} />}
```

2024-10-19 20:04 UTC, Waldo33 commented on packages/client/src/processes/auth/api/authApi.ts
> +const BASE_AUTH_API = 'https://ya-praktikum.tech/api/v2/auth'
Как вариант, можно вынести ссылку на API в .env файл проекта при желании

2024-10-19 20:04 UTC, Waldo33 commented on packages/client/src/processes/auth/api/authApi.ts
> +  const response = await fetch(`${BASE_AUTH_API}/signin`, {
Почему решил использовать fetch, а не axios?

2024-10-19 20:04 UTC, Waldo33 commented on packages/client/src/processes/auth/model/authSlice.ts
> +        state.error = action.payload || 'An unknown error occurred'
Можно не дублировать текст ошибки каждый раз, а вынести в хелпер, как вариант и переиспользовать

2024-10-19 20:04 UTC, Waldo33 commented on packages/client/src/processes/auth/model/thunks.ts
> +      return rejectWithValue((err as Error).message)
Возможно стоит сделать Type Guard с проверкой наличия поля message? нет гарантии что в catch не прилетит что-то другое в будущем

2024-10-19 20:04 UTC, Waldo33 commented on packages/client/vite.config.ts
> +        // '@features': path.resolve(__dirname, 'src/features/'),
Предлагаю тут так же либо не трогать алиасы, либо удалить

2024-10-21 21:32 UTC, Waldo33 commented on packages/client/src/app/router.tsx
> +    loader: async () => {
Давай вынесем функцию отдельно и сюда будем прокидывать?

2024-10-21 21:33 UTC, Waldo33 commented
Конфликты появились, надо зарешать

2024-10-22 06:51 UTC, Waldo33 approved these changes

2024-10-22 15:34 UTC, kyzinatra commented on packages/client/src/processes/auth/model/authSlice.ts
> +      })
Круто, что вы обрабатываете ошибки

2024-10-22 15:35 UTC, kyzinatra commented on packages/client/src/processes/auth/ui/SigninForm.tsx
> +      password: '',
Круто, что вы используете zod валидацию

2024-10-22 15:36 UTC, kyzinatra approved these changes
Отличная верстка страниц. Хорошее подключени api и валидация! Вопросов по этой части нет. Хорошая декомпозиция компонентов

2024-10-22 15:42 UTC, merged