feat: added get user data and themes
Waldo33/middle.game.praktikum.yandex pull request #41
Opened 2024-12-11 19:08 UTC by spiritius

### Какую задачу решаем

**Переключение темы (бэкенд)**

- добавлены модели для таблиц users и themes
- добавлена миграция для первичного заполнения таблицы themes, реализация на sequelize-cli: `yarn sequelize-cli db:migrate`
- добавлена проверка пользователя при аутинтификации: если пользователя нет в базе, он добавляется с темой по умолчанию
- добавлены две ручки для получения данных о пользователе (id и theme_id) и для обновления theme_id при ее смене

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-12-11 20:48 UTC, Waldo33 commented on packages/server/middleware/auth.ts
> +interface YandexUser {
Тут уже наверное лучше dev подтянуть, я получение юзера сделал

2024-12-11 20:54 UTC, Waldo33 commented on packages/server/routes/user.ts
> +router.post('/set/theme', changeUser)
В REST API принято оперировать сущностями, действий в путях не должно быть

То есть должно быть что-то типо POST /user/theme судя по всему

2024-12-11 20:55 UTC, Waldo33 commented on packages/server/models/user.ts
> +User.init(
Подскажи, для чего нам сущность юзера в своей таблице хранить и отдавать, почему не можем использовать данные того юзера что от Яндекса приходит?

Не вижу причин не использовать данные из getYandexUser

2024-12-11 20:56 UTC, Waldo33 commented on packages/server/controllers/user.ts
> +export const changeUser = async (
Для чего нам оперировать в User, почему бы просто тему по запросу не менять?

2024-12-11 20:57 UTC, Waldo33 commented on packages/server/config/config.json
> +  "production": {
Где сейчас эти данные используются?

Секреты не принято в коде хранить, так делать нельзя

2024-12-11 20:59 UTC, Waldo33 requested changes
Предлагаю удалить секреты из кода и избавиться от лишних сущностей, оперируя только сущностью темы. Храня темы по userId из практикума, это позволит большую часть кода выпилить сейчас.

2024-12-12 04:57 UTC, spiritius commented on packages/server/models/user.ts
> +User.init(
Нам нужно хранить связку user_id + theme_id, как это делать без таблицы с пользователем?

2024-12-12 04:58 UTC, spiritius commented on packages/server/controllers/user.ts
> +export const changeUser = async (
Потому что тема хранится у каждого авторизованного юзера в профиле

2024-12-12 05:02 UTC, spiritius commented on packages/server/config/config.json
> +  "production": {
Эти данные используются для миграций
Посмотрю что можно сделать

2024-12-12 05:04 UTC, spiritius commented
> Предлагаю удалить секреты из кода и избавиться от лишних сущностей, оперируя только сущностью темы. Храня темы по userId из практикума, это позволит большую часть кода выпилить сейчас.

В теории практикума описана последовательность работы с темизацией: используем две таблицы, одна для списка тем, другая - со списком пользователей и привязанных тем.

2024-12-12 16:47 UTC, Waldo33 commented on packages/server/api/yandexPraktikum.ts
> +export const checkUser = async (yandexUser: LocalUser) => {
Этот код нужно перенести в UserService, по смыслу этот код не проверяет наличие, а еще и создает, что не совсем честно

Я вижу это так, что нужно создать 2 метода - isExist и create

По идее и работу с практикумом тоже надо в сервис юзера вынести, но это я пожалуй сам отрефакторю, сам написал сам и исправлю:)

Так же не совсем понимаю зачем externalId в виде строки передавать

2024-12-12 16:48 UTC, Waldo33 commented on packages/server/constants/index.ts
> +  USER_NOT_FOUND: 'User not found',
Такую ошибку предлагаю рядом с моделью положить, по аналогии с другими моделями

2024-12-12 16:49 UTC, spiritius commented on packages/server/api/yandexPraktikum.ts
> +export const checkUser = async (yandexUser: LocalUser) => {
>зачем externalId в виде строки передавать 
потому что приходящий ид может быть чем угодно (если держать в уме не только бэк практикума)

2024-12-12 16:51 UTC, spiritius commented on packages/server/constants/index.ts
> +  USER_NOT_FOUND: 'User not found',
оно вынесено. отсюда не удалила)

2024-12-12 16:59 UTC, Waldo33 commented on packages/server/middleware/auth.ts
> +    const userId = await checkUser(data)
Обновление юзера здесь повлияет на время выполнения всех других запросах, все таки при текущем юзере предлагаю выполнять это действие при изменении темы

Юзера яндекса можно будет в методе смены получить из кэша по ключу `yandexUser_${uuid}`, но для этого здесь надо будет прокинуть req.params.yandex_uuid = uuid

2024-12-12 17:00 UTC, Waldo33 requested changes
Осталась пара небольших замечаний, во всем остальном мне нравится как теперь реализована задача

2024-12-12 17:01 UTC, spiritius commented on packages/server/middleware/auth.ts
> +    const userId = await checkUser(data)
нам нужно при логине пользователя найти его в своей базе (и добавить, если его нет). это иденственная функция checkUser

2024-12-12 17:02 UTC, Waldo33 commented on packages/server/api/yandexPraktikum.ts
> +export const checkUser = async (yandexUser: LocalUser) => {
На текущий момент мы работаем с практикумом, не вижу смысла писать на случай "а что если", но не настаиваю касательно приведения

2024-12-12 17:04 UTC, Waldo33 commented on packages/server/api/yandexPraktikum.ts
> +export const checkUser = async (yandexUser: LocalUser) => {
Ты говоришь, что могут быть externalId из других сервисов, но я не представляю как такие неконсистентные данные можно хранить в одной таблице.

Что если у двух разных сервисов будет одинаковый айдишник, но при этом пользователи на деле разные?

2024-12-12 20:18 UTC, Waldo33 approved these changes

2024-12-13 06:52 UTC, kyzinatra approved these changes
Отличная реализация темизации на стороне сервера. Есть небольшой комменатрий по поводу логов. Все же рекомендую на сервере использовать winsoton. В остальном все хорошо, так что принимаю вашу работа
Желаю успехов в дальнейшем обучении

2024-12-13 06:52 UTC, kyzinatra commented on packages/server/controllers/user.ts
> +      console.log(error)
Такие логи стоит убрать. Можно добавить логирование в файл к примеру с помощью `winston`

2024-12-13 07:31 UTC, Waldo33 commented on packages/server/controllers/user.ts
> +      console.log(error)
Он уже даже есть и уже пишет логи:)

2024-12-13 07:56 UTC, kyzinatra commented on packages/server/controllers/user.ts
> +      console.log(error)
Тогда тем более от сюда убрать логи)

2024-12-13 08:17 UTC, merged