Emoji api
Waldo33/middle.game.praktikum.yandex pull request #43
Opened 2024-12-15 16:16 UTC by galnikolai

### Какую задачу решаем

Emoji API

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-12-15 16:56 UTC, Waldo33 requested changes

2024-12-15 16:56 UTC, Waldo33 commented on packages/server/controllers/reaction.ts
> +      const existingReaction = await Reaction.findOne({
Предлагаю по аналогии с топиками сделать - логика работы с данными в сервисе, работа с ORM в репозитории

2024-12-15 16:59 UTC, Waldo33 commented on packages/server/models/reaction.ts
> +    topicId: {
Между моделями можно задавать связи, как например между топиком и комментариями

2024-12-16 03:33 UTC, galnikolai commented on packages/server/controllers/reaction.ts
> +      const existingReaction = await Reaction.findOne({
Сделал по аналогии

2024-12-16 03:33 UTC, galnikolai commented on packages/server/models/reaction.ts
> +    topicId: {
Точно

2024-12-16 06:31 UTC, Waldo33 approved these changes

2024-12-16 06:31 UTC, Waldo33 commented on packages/server/routes/topic.ts
> +router.get(
Можно получать реакции в GET /api/topics/:id по аналогии, как получаем комментарии при запросе топика, но это уже по желанию

2024-12-17 00:37 UTC, merged