Leaderboard #11
Waldo33/middle.game.praktikum.yandex pull request #6
Opened 2024-10-21 01:08 UTC by marie-uglova

### Какую задачу решаем
Сверстать страницу лидерборд

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-10-21 04:11 UTC, spiritius requested changes

2024-10-21 04:11 UTC, spiritius commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +      <h1>Лидерборд</h1>
В чанке `<Intro />` есть тег `<h1>`. Получается, два тега на странице.
Можно исправить в чанке на `<h2 className="h1">`, либо исправить тут на `<h2 className="h1">`

Плюс, заголовок "Лидерборд" сильно прилепает к `<Intro />`, хорошо бы его пододвинуть ниже.

В остальном - мне оч нравится, лаконично и чисто! 👌

2024-10-21 05:24 UTC, Waldo33 requested changes
Очень хорошо, что ты отдельно вынесла моковые данные!)
Прикрепляю отдельно моменты, на которые стоит обратить внимание

2024-10-21 05:24 UTC, Waldo33 commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardBody.tsx
> +import { LeaderboardListProps } from '@pages/LeaderboardPage/types'
По FSD модуль внутри себя должен использовать относительные импорты, а не абсолютные, то есть тебе здесь нужно заменить импорт на "../types"

2024-10-21 05:24 UTC, Waldo33 commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +import { Leaderboard } from '@pages/LeaderboardPage/types'
Аналогично советую обратить внимание на импорты внутри одного модуля

2024-10-21 05:24 UTC, Waldo33 commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardBody.tsx
> +export const LeaderboardBody: FC<LeaderboardListProps> = ({ list }) => {
Компонент выглядит так, словно в него можно засунуть всю таблицу (все таки TableRow трудно переиспользовать в отдельности без самой таблицы, что лишает смысла выносить эту часть в компонент) и спустить на уровень widgets, а на странице лидерборда просто использовать. 
Оставляю на твое усмотрение

2024-10-21 15:21 UTC, marie-uglova commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardBody.tsx
> +export const LeaderboardBody: FC<LeaderboardListProps> = ({ list }) => {
Я изначально так и сделала, потом решила перестраховаться))

2024-10-24 17:26 UTC, Waldo33 requested changes

2024-10-24 17:26 UTC, Waldo33 commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +import { Intro } from '@pages/MainPage/ui/Intro'
Чтобы не было импорта с того же уровна, судя по всему нужно Intro вынести в widgets

2024-10-24 17:26 UTC, Waldo33 commented on packages/client/src/pages/LeaderboardPage/ui/LeaderboardPage.tsx
> +import { LeaderboardTable } from './LeaderboardTable'
Тоже можно на уровень widgets

2024-10-24 17:26 UTC, Waldo33 commented on packages/client/src/pages/MainPage/ui/Intro.tsx
> -      <h1 className="intro__title">
Снова классы по БЭМ, почему бы не переделать на модули?:)

2024-10-24 17:31 UTC, spiritius commented on packages/client/src/pages/MainPage/ui/Intro.tsx
> -      <h1 className="intro__title">
intro - это кусок из главной страницы, я его делала без мысли о том, чтобы использовать где-то еще. но раз используем, то можно вынести в widgets

насчет бэм и модулей - дело удобства. думаю, стоило об этом договориться до того, как все начали верстать свои куски) а сейчас мы задерживаем Машу. предлагаю оставить в качестве техдолга.

2024-10-27 16:51 UTC, Waldo33 approved these changes

2024-10-27 18:30 UTC, merged