5 Вёрстка страницы ошибок 500
Waldo33/middle.game.praktikum.yandex pull request #8
Opened 2024-10-21 19:44 UTC by marie-uglova

### Какую задачу решаем
Вёрстка страницы ошибок 500

### Скриншоты/видяшка (если есть)
![111](https://github.com/user-attachments/assets/2305ab3a-1fcc-4e8c-9d6f-3a898cf1558a)

### TBD (если есть)

2024-10-23 07:04 UTC, galnikolai requested changes

2024-10-23 07:04 UTC, galnikolai commented on packages/client/src/pages/NotFoundPage/ui/NotFoundPage.tsx
> +        <a href="/">главную</a>
В React нужно использовать Link для переходов

2024-10-24 13:43 UTC, galnikolai approved these changes

2024-10-24 13:48 UTC, galnikolai commented on packages/client/src/pages/NotFoundPage/ui/NotFoundPage.tsx
> +        <Link to="/" onClick={() => navigate(-1)}>
Тут две конфликтующие инструкции: to="/" и onClick={() => navigate(-1)}.

	•	to="/" по идее всегда ведет на главную страницу.
	•	onClick={() => navigate(-1)} пытается вернуть на предыдущую страницу.

по идее нужно оставить только: `onClick={() => navigate(-1)}`

2024-10-24 14:00 UTC, galnikolai commented on packages/client/src/pages/NotFoundPage/ui/NotFoundPage.tsx
> +        <Link to="/" onClick={() => navigate(-1)}>
Я так понимаю, что в 400 ошибке подобно

2024-10-27 12:27 UTC, Waldo33 commented on packages/client/src/pages/NotFoundPage/ui/NotFoundPage.tsx
> +        <Link to="/" onClick={() => navigate(-1)}>
> по идее нужно оставить только: `onClick={() => navigate(-1)}` и заменить компонент Link на обычный div, застилизовав, чтобы визуально div был как Link

Еще лучше если будет button, а не div, по семантике это лучше :)

2024-10-27 17:00 UTC, galnikolai approved these changes

2024-10-27 18:30 UTC, merged