Feature/base mechanics for game
Waldo33/middle.game.praktikum.yandex pull request #9
Opened 2024-10-22 17:00 UTC by Waldo33

### Какую задачу решаем
Базовая механика игры

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-10-23 15:56 UTC, galnikolai commented on packages/client/src/widgets/Game/lib/GameClass.ts
Нравится как декомпозировал классы и методы! Легко читаются

2024-10-23 18:39 UTC, galnikolai requested changes

2024-10-23 18:39 UTC, galnikolai commented on packages/client/src/widgets/Game/lib/GameBoardClass.ts
Глобально, на данный момент, здесь все окей, класс чуть чуть перегружен, но не критично, в будущем, если добавлять расширять можно будет декомпозировать на визуализацию(класс аля GameRenderer ) и взаимодействие + действительно Eventbus тоже был бы не лишним, нужно не забыть добавить

2024-10-23 18:39 UTC, galnikolai commented on packages/client/src/widgets/Game/lib/TimerClass.ts
> +  public stopTimer() {
Как будто стоит еще обнулять, на будущее, если будет использоваться для сравнения или еще чего

`this.intervalId = null`

2024-10-23 18:40 UTC, galnikolai commented on packages/client/src/widgets/Game/lib/GameBoardClass.ts
Глобально, на данный момент, здесь все окей, класс чуть чуть перегружен, но не критично, в будущем, если добавлять расширять можно будет декомпозировать на визуализацию(класс аля GameRenderer ) и взаимодействие + действительно Eventbus тоже был бы не лишним, нужно не забыть добавить

2024-10-23 20:17 UTC, Waldo33 commented on packages/client/src/widgets/Game/lib/GameBoardClass.ts
EventBus уже есть, просто используется не везде. 
С одной стороны классы друг с другом логически связаны и ничего плохого что один инжектит другой, в данном случае (по моему скромному мнению).
Вот сильная связность компонентов это плохо.
Надеюсь ревьюер мне что-то по этому поводу сможет рассказать, было бы интересно

2024-10-23 20:19 UTC, Waldo33 commented on packages/client/src/widgets/Game/lib/TimerClass.ts
> +  public stopTimer() {
По сути его и не придется занулять, если каждый раунд будет создаваться новый класс таймера
Но если думаешь что необходимо, то добавлю

2024-10-23 20:36 UTC, galnikolai approved these changes

2024-10-23 20:37 UTC, galnikolai commented on packages/client/src/widgets/Game/lib/GameBoardClass.ts
Конечно же видел EventBus, то, что не везде используется и имел в виду

2024-10-23 20:39 UTC, galnikolai commented on packages/client/src/widgets/Game/lib/GameBoardClass.ts
Вместе почитаем комменты ревьюера

2024-10-24 07:33 UTC, kyzinatra commented on packages/client/src/pages/GamePage/lib/helpers/index.ts
> +    2,
Форматировать время можно с помощью объекта `Intl`. Очень удобно

2024-10-24 07:34 UTC, kyzinatra commented on packages/client/src/shared/lib/classes/EventBus.ts
> +> {
Хорошая типизация

2024-10-24 08:01 UTC, kyzinatra commented on packages/client/src/widgets/Game/lib/GameBoardClass.ts
Действительно. Я согласен, что компоненты немного перегружены. Выбранный подход с `EventBus` хорошо ложится на MVP паттерн. В таком случае я бы рекомендовал бы вам разделить логику на слои и не допускать того, чтобы какой-то из классов нарушал `Single rensponsibility`, то есть имел больше 1 причины для изменений. В вашем случае `GameBoard` к примеру занимается и отрисовкой и логикой. Причем довольно разной. Разобраться с этим вам поможет более активное использование `EventBus`. К примеру логика может быть такая

```js

bus.on(/(init)|(restart)/, () => { // Рекомендую добавить регулярки

GameFieldView.renderField(CardView) // Замечу, что GameFieldView без разницы какие карточки рендерить. Он их принимает сверху

})

// GameFieldView

renderField(Cards: Cards[]) {
    // тут к примеру цикл
    this.field.render(i, j, Card[i * n + j].render())
}

```

Замечу, что презентор (То есть `EventBus`) может использоваться и общаться и с View и c Model, но при этом Modal и View не могут общаться между собой. 

```js

bus.on(/shuffle/, (shuffeledCard) => {
    const cards = shuffeledCard.map((el) => new Card(el))
    GameFieldView.renderField(cards)
})

```

В целом логика должна быть построена на том, что Пользователь отправляет событие во View. Там его ловит addEventListener и передает событие в eventBus. Который в свою очередь его как-то обрабатывает и обновляет UI и Model. В свою очередь изменения в Модели также могут обновить презентер, который может обновить UI (к примеру таймер)

В общем примерно такая структура кажется идеальной в случае использования `eventBus`. Постарался подробно описать как это бы выглядело с точки зрения архитектуры. Если остались вопросы, то можете ответить тут, только поставьте отметку `@kyzinatra`

2024-10-24 08:05 UTC, kyzinatra commented on packages/client/src/widgets/Game/lib/GameBoardClass.ts
> +
Круто, что используете модификаторы доступа

2024-10-24 08:07 UTC, kyzinatra approved these changes
Отличная работа! Выстраивание логики в ООП стиле всегда не простая задача. Вы выбрали хороших подход с EventBus. Я постарался описать как его можно улучшить наложив на него более строгие органичение паттерна MVP. 
Это в целом довольно продвинутый уровень, так как требует опыта в проектирвании систем. Но мне тем не менее понравилось, что вы выносите части логики и стараетесь не созвдавать божественных классов. Если будут вопросы по этой части то можете тэгнуть меня и я отвечу

(Описал подход в ответе к 1 из комментариев ваших коллег)

2024-10-24 17:31 UTC, Waldo33 commented
> Отличная работа! Выстраивание логики в ООП стиле всегда не простая задача. Вы выбрали хороших подход с EventBus. Я постарался описать как его можно улучшить наложив на него более строгие органичение паттерна MVP. 
> 
> Это в целом довольно продвинутый уровень, так как требует опыта в проектирвании систем. Но мне тем не менее понравилось, что вы выносите части логики и стараетесь не созвдавать божественных классов. Если будут вопросы по этой части то можете тэгнуть меня и я отвечу
> 
> 
> 
> (Описал подход в ответе к 1 из комментариев ваших коллег)

Хотелось бы поподробнее расспросить про то, к чему стремиться?
Идеальный вариант это свой реактивный фреймворк, только у которого компоненты рендерятся в канвасе?

2024-10-24 20:02 UTC, Waldo33 commented on packages/client/src/pages/GamePage/lib/helpers/index.ts
> +    2,
@kyzinatra не могу придумать здесь решения с Intl, которое было бы более удобным, разве что можно сделать форматтер по типу
```
const formatter = new Intl.NumberFormat('en-US', {
    minimumIntegerDigits: 2,
    useGrouping: false,
  });
```
Но придется все равно высчитать минуты и секунды, что не сократит код

А если например применить Date?
```
const getTimePad = (timeInSec) => new Date(timeInSec * 1000).toISOString().slice(14, 19);
```

2024-10-24 20:02 UTC, Waldo33 commented on packages/client/src/widgets/Game/lib/GameBoardClass.ts
@kyzinatra да, твой вариант выглядит действительно круче чем текущий.
Мы можем отрефакторить это в будущих спринтах, правильно понимаю?

2024-10-24 20:11 UTC, kyzinatra commented on packages/client/src/pages/GamePage/lib/helpers/index.ts
> +    2,
А разве этот метод не подойдет ?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat

2024-10-24 20:12 UTC, kyzinatra commented on packages/client/src/pages/GamePage/lib/helpers/index.ts
> +    2,
> А разве этот метод не подойдет ? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat

Я сейчас подумал. Может быть правда не подойдет в вашем случае. Тогда решение с Date выглядит хорошо. Мне нравится

2024-10-24 20:13 UTC, kyzinatra commented on packages/client/src/widgets/Game/lib/GameBoardClass.ts
Да, так и есть. Можете сделать это в следующем спринте

2024-10-24 21:31 UTC, Waldo33 commented on packages/client/src/pages/GamePage/lib/helpers/index.ts
> +    2,
@kyzinatra хорошо, залил изменения

2024-10-24 21:34 UTC, Waldo33 commented on packages/client/src/pages/GamePage/lib/helpers/index.ts
> +    2,
> > А разве этот метод не подойдет ? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat
> 
> Я сейчас подумал. Может быть правда не подойдет в вашем случае. Тогда решение с Date выглядит интересно. Мне нравится

Решение в духе codewars:))

2024-10-25 06:35 UTC, merged